const rawData = {
  count: 71,
  next: null,
  previous: null,
  results: [
    {
      id: 5,
      user: {
        id: 11,
        username: 'yusufst2',
        first_name: 'John',
        display_name: 'John Travolta',
        email: 'suryayusuf00@gmail.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 1,
          name: 'QA Prosa',
        },
        phone_number: '',
        voice_model: '/media/voice_model/yusufst2/audi3_20220606_152902.wav',
        last_login: '2022-08-23T16:25:21.832357',
        count_participated_meetings: 15,
        count_attended_meetings: 3,
      },
      organization: {
        id: 1,
        name: 'QA Prosa',
      },
      position: 'QA',
      department: 'Tester',
      is_active: true,
      role: 'Member',
    },
    {
      id: 6,
      user: {
        id: 12,
        username: 'test2',
        first_name: 'test',
        display_name: 'test dua',
        email: 'test2@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 1,
          name: 'QA Prosa',
        },
        phone_number: '',
        voice_model: '/media/voice_model/test2/blob_20220906_142108.wav',
        last_login: '2022-11-08T11:01:55.600833',
        count_participated_meetings: 22,
        count_attended_meetings: 6,
      },
      organization: {
        id: 1,
        name: 'QA Prosa',
      },
      position: 'QA',
      department: 'Tester',
      is_active: true,
      role: 'Member',
    },
    {
      id: 49,
      user: {
        id: 41,
        username: 'test6',
        first_name: 'test',
        display_name: 'test yahoo',
        email: 'test6@prosa.ai',
        avatar: null,
        enrollment_status: 'enrolled',
        is_enrolling: false,
        organization: {
          id: 1,
          name: 'QA Prosa',
        },
        phone_number: '',
        voice_model: '/media/voice_model/test6/20s.mp3',
        last_login: null,
        count_participated_meetings: 4,
        count_attended_meetings: 0,
      },
      organization: {
        id: 1,
        name: 'QA Prosa',
      },
      position: 'QA',
      department: 'Tester',
      is_active: true,
      role: 'Member',
    },
    {
      id: 50,
      user: {
        id: 4,
        username: 'qaanalyst',
        first_name: 'Test',
        display_name: 'Test akun Admin',
        email: 'test1@prosa.ai',
        avatar: '/media/avatar/qaanalyst/sticker_meal_ville_1.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 1,
          name: 'QA Prosa',
        },
        phone_number: '12345678901234',
        voice_model: null,
        last_login: '2023-10-10T16:13:20.195376',
        count_participated_meetings: 32,
        count_attended_meetings: 5,
      },
      organization: {
        id: 1,
        name: 'QA Prosa',
      },
      position: 'QA',
      department: 'Tester',
      is_active: true,
      role: 'Admin',
    },
    {
      id: 7,
      user: {
        id: 8,
        username: 'yusufst',
        first_name: 'Yusuf Surya',
        display_name: 'Yusuf Surya Tryantono',
        email: 'yusuf.tryantono@prosa.ai',
        avatar: '/media/avatar/yusufst/2825710.gif',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 1,
          name: 'QA Prosa',
        },
        phone_number: '1234567890123',
        voice_model: '/media/voice_model/yusufst/audi1_20220614_114702.wav',
        last_login: '2022-10-26T14:56:05.505754',
        count_participated_meetings: 33,
        count_attended_meetings: 4,
      },
      organization: {
        id: 1,
        name: 'QA Prosa',
      },
      position: 'QA',
      department: 'Tester',
      is_active: true,
      role: 'Member',
    },
    {
      id: 8,
      user: {
        id: 61,
        username: 'testyahya',
        first_name: 'Yahya',
        display_name: 'Yahya Yahya',
        email: '13518029@std.stei.itb.ac.id',
        avatar: null,
        enrollment_status: 'enrolling',
        is_enrolling: true,
        organization: {
          id: 1,
          name: 'QA Prosa',
        },
        phone_number: '',
        voice_model: '/media/voice_model/testyahya/blob.wav',
        last_login: null,
        count_participated_meetings: 5,
        count_attended_meetings: 0,
      },
      organization: {
        id: 1,
        name: 'QA Prosa',
      },
      position: 'SE',
      department: 'SE',
      is_active: true,
      role: 'Member',
    },
    {
      id: 10,
      user: {
        id: 1,
        username: 'user.account',
        first_name: '',
        display_name: 'user.account',
        email: 'meemo@prosa.ai',
        avatar: '/media/avatar/user.account/Mask_Group_1.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 1,
          name: 'QA Prosa',
        },
        phone_number: '',
        voice_model: '/media/voice_model/user.account/blob_20220616_234801.wav',
        last_login: '2023-10-11T14:21:45.257468',
        count_participated_meetings: 3,
        count_attended_meetings: 0,
      },
      organization: {
        id: 1,
        name: 'QA Prosa',
      },
      position: 'QAa',
      department: 'qa',
      is_active: true,
      role: 'Admin',
    },
    {
      id: 30,
      user: {
        id: 103,
        username: 'widyaput',
        first_name: 'Widya',
        display_name: 'Widya Putra',
        email: 'widya.putra@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 12,
          name: 'ProsatmfG',
        },
        phone_number: '6285640740549',
        voice_model: '/media/voice_model/widyaput/blob_20220902_114755.wav',
        last_login: '2022-09-02T11:30:50.278762',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 12,
        name: 'ProsatmfG',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 58,
      user: {
        id: 135,
        username: 'test1',
        first_name: 'Test',
        display_name: 'Test admin dua',
        email: 'yusufsuryat123t@gmail.com',
        avatar: '/media/avatar/test1/D4.2.1.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 30,
          name: 'Qa Prosa',
        },
        phone_number: '6211211111111',
        voice_model: '/media/voice_model/test1/audi1_20221003_101211.wav',
        last_login: '2022-11-17T09:51:13.214610',
        count_participated_meetings: 3,
        count_attended_meetings: 1,
      },
      organization: {
        id: 30,
        name: 'Qa Prosa',
      },
      position: 'QA',
      department: 'QA',
      is_active: true,
      role: 'Member',
    },
    {
      id: 57,
      user: {
        id: 134,
        username: 'test',
        first_name: 'test',
        display_name: 'test test',
        email: 'yususurya5000@prosa.ai',
        avatar: '/media/avatar/test/D4.2.1.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 30,
          name: 'Qa Prosa',
        },
        phone_number: '6212312312',
        voice_model: '/media/voice_model/test/blob_20221101_193644.wav',
        last_login: '2022-11-17T15:31:32.383879',
        count_participated_meetings: 1,
        count_attended_meetings: 0,
      },
      organization: {
        id: 30,
        name: 'Qa Prosa',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 59,
      user: {
        id: 140,
        username: 'admin_collab',
        first_name: 'Akun',
        display_name: 'Akun Demo',
        email: 'admin@collab.ai',
        avatar: '/media/avatar/admin_collab/264069.jpg',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 32,
          name: 'Collab Org',
        },
        phone_number: '',
        voice_model:
          '/media/voice_model/admin_collab/Enroll%20Hakim%20Ketua_20221101_192901.wav',
        last_login: '2023-03-16T16:25:01.610082',
        count_participated_meetings: 1,
        count_attended_meetings: 0,
      },
      organization: {
        id: 32,
        name: 'Collab Org',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 60,
      user: {
        id: 141,
        username: 'member_collab_1',
        first_name: 'Member',
        display_name: 'Member Collab 1',
        email: 'member1@collab.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 32,
          name: 'Collab Org',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2022-11-04T12:27:26.988067',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 32,
        name: 'Collab Org',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 61,
      user: {
        id: 142,
        username: 'member_collab 2',
        first_name: 'Member',
        display_name: 'Member Collab 2',
        email: 'member2@collab.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 32,
          name: 'Collab Org',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2022-11-01T18:53:39.972105',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 32,
        name: 'Collab Org',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 62,
      user: {
        id: 144,
        username: 'ut1',
        first_name: 'UT1',
        display_name: 'UT1 ',
        email: 'usagetracker@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 33,
          name: 'UT1',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2022-11-07T07:52:31.270853',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 33,
        name: 'UT1',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 63,
      user: {
        id: 145,
        username: 'ut2',
        first_name: 'UT2',
        display_name: 'UT2 ',
        email: 'usagetracker1@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 33,
          name: 'UT1',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 33,
        name: 'UT1',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 64,
      user: {
        id: 146,
        username: 'ut3',
        first_name: 'UT3',
        display_name: 'UT3 ',
        email: 'usagetracker2@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 33,
          name: 'UT1',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 33,
        name: 'UT1',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 65,
      user: {
        id: 148,
        username: 'y3',
        first_name: 'Yusuf',
        display_name: 'Yusuf Surya',
        email: 'yusufsuryatt@gmail.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 34,
          name: 'QA*___B7KQ',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2022-11-15T08:02:26',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 34,
        name: 'QA*___B7KQ',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 66,
      user: {
        id: 151,
        username: 'sample_erlin',
        first_name: 'Sample Erlin',
        display_name: 'Sample Erlin Widya',
        email: 'erlin@example.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 35,
          name: 'Sample',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2022-12-19T22:10:56.751380',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 35,
        name: 'Sample',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 67,
      user: {
        id: 149,
        username: 'sample_rahmi',
        first_name: 'Sample Rahmi',
        display_name: 'Sample Rahmi Yuwan',
        email: 'rahmi@example.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 35,
          name: 'Sample',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 35,
        name: 'Sample',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 68,
      user: {
        id: 150,
        username: 'sample_sazky',
        first_name: 'Sample Sazky',
        display_name: 'Sample Sazky Reza',
        email: 'sazky@example.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 35,
          name: 'Sample',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 35,
        name: 'Sample',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 69,
      user: {
        id: 152,
        username: 'sample_trisa',
        first_name: 'Sample Trisa',
        display_name: 'Sample Trisa Sepdiani',
        email: 'trisa@example.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 35,
          name: 'Sample',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 35,
        name: 'Sample',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 99,
      user: {
        id: 186,
        username: 'einzuji',
        first_name: 'Nanda',
        display_name: 'Nanda BE',
        email: 'einzuji@gmail.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 54,
          name: 'Prosa*___4jC2',
        },
        phone_number: '6282326895333',
        voice_model: null,
        last_login: '2023-03-28T16:05:11.641049',
        count_participated_meetings: 1,
        count_attended_meetings: 0,
      },
      organization: {
        id: 54,
        name: 'Prosa*___4jC2',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 115,
      user: {
        id: 204,
        username: 'aditya.pratama',
        first_name: 'Aditya',
        display_name: 'Aditya Pratama',
        email: 'aditya.pratama@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 57,
          name: 'Prosa Leaders',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 57,
        name: 'Prosa Leaders',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 110,
      user: {
        id: 199,
        username: 'dessipuji',
        first_name: 'Dessi',
        display_name: 'Dessi Puji Lestari',
        email: 'dessipuji@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 57,
          name: 'Prosa Leaders',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 57,
        name: 'Prosa Leaders',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 111,
      user: {
        id: 200,
        username: 'devin.hoesen',
        first_name: 'Devin',
        display_name: 'Devin Hoesen',
        email: 'devin.hoesen@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 57,
          name: 'Prosa Leaders',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-03-03T16:04:46.819254',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 57,
        name: 'Prosa Leaders',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 117,
      user: {
        id: 206,
        username: 'donny.adhitama',
        first_name: 'Donny',
        display_name: 'Donny Mirza Adhitama',
        email: 'donny.adhitama@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 57,
          name: 'Prosa Leaders',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 57,
        name: 'Prosa Leaders',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 112,
      user: {
        id: 201,
        username: 'iftitakhul.zakiah',
        first_name: 'Iftitakhul',
        display_name: 'Iftitakhul Zakiah',
        email: 'iftitakhul.zakiah@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 57,
          name: 'Prosa Leaders',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-05-12T08:01:14.846403',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 57,
        name: 'Prosa Leaders',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 116,
      user: {
        id: 205,
        username: 'miswanto',
        first_name: 'Miswanto',
        display_name: 'Miswanto ',
        email: 'miswanto@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 57,
          name: 'Prosa Leaders',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 57,
        name: 'Prosa Leaders',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 113,
      user: {
        id: 202,
        username: 'reza.nawawi',
        first_name: 'Reza',
        display_name: 'Reza Fadjar Nawawi',
        email: 'reza.nawawi@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 57,
          name: 'Prosa Leaders',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-04-03T08:18:54.602897',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 57,
        name: 'Prosa Leaders',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 114,
      user: {
        id: 203,
        username: 'rizki.ginanjar',
        first_name: 'Rizki',
        display_name: 'Rizki Rivai Ginanjar',
        email: 'rizki.ginanjar@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 57,
          name: 'Prosa Leaders',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 57,
        name: 'Prosa Leaders',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 119,
      user: {
        id: 208,
        username: 'admin_persidangan',
        first_name: 'Admin',
        display_name: 'Admin Persidangan',
        email: 'admin_kejagung@trial.prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 59,
          name: 'Kejaksaan Agung',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-03-07T16:36:19.113774',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 59,
        name: 'Kejaksaan Agung',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 120,
      user: {
        id: 209,
        username: 'member_persidangan_1',
        first_name: 'Pencatat',
        display_name: 'Pencatat Persidangan 1',
        email: 'kejagung_1@trial.prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 59,
          name: 'Kejaksaan Agung',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 59,
        name: 'Kejaksaan Agung',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 121,
      user: {
        id: 210,
        username: 'member_persidangan_2',
        first_name: 'Pencatat',
        display_name: 'Pencatat Persidangan 2',
        email: 'kejagung_2@trial.prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 59,
          name: 'Kejaksaan Agung',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 59,
        name: 'Kejaksaan Agung',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 123,
      user: {
        id: 212,
        username: 'qa_addterm',
        first_name: 'Nadira',
        display_name: 'Nadira Arthamevia',
        email: 'nadira.arthamevia@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 61,
          name: 'qa sembilan*___KVG4',
        },
        phone_number: '628119192472',
        voice_model: null,
        last_login: '2023-10-09T15:17:52.842425',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 61,
        name: 'qa sembilan*___KVG4',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 125,
      user: {
        id: 214,
        username: 'fakhrisurya',
        first_name: 'fakhri',
        display_name: 'fakhri surya',
        email: 'koko@koko.koko',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 63,
          name: 'Fakhri test*___YpWE',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-07-21T12:57:11.997156',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 63,
        name: 'Fakhri test*___YpWE',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 126,
      user: {
        id: 215,
        username: 'trial_demo',
        first_name: 'Trial',
        display_name: 'Trial Demo',
        email: 'demo@trial.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 64,
          name: 'Trial Demo',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-10-06T09:09:25.851635',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 64,
        name: 'Trial Demo',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 127,
      user: {
        id: 216,
        username: 'isalbani',
        first_name: 'Isal',
        display_name: 'Isal Bani',
        email: 'isal@bani.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 65,
          name: 'Prosa*___Fd1w',
        },
        phone_number: '085576554322',
        voice_model: null,
        last_login: '2023-10-11T10:13:13.623455',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 65,
        name: 'Prosa*___Fd1w',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 128,
      user: {
        id: 217,
        username: 'isalbanuy',
        first_name: 'Isal',
        display_name: 'Isal Banuy',
        email: 'sal@banuy.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 66,
          name: 'Prosa*___ETQX',
        },
        phone_number: '087765543223',
        voice_model: null,
        last_login: '2023-04-12T12:17:53.322216',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 66,
        name: 'Prosa*___ETQX',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 133,
      user: {
        id: 222,
        username: 'member_speech_1',
        first_name: 'Speech',
        display_name: 'Speech 1',
        email: 'member1@speech.prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 71,
          name: 'Speech',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 71,
        name: 'Speech',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 134,
      user: {
        id: 223,
        username: 'member_speech_2',
        first_name: 'Speech',
        display_name: 'Speech 2',
        email: 'member2@speech.prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 71,
          name: 'Speech',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 71,
        name: 'Speech',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 132,
      user: {
        id: 221,
        username: 'admin_speech',
        first_name: 'Speech',
        display_name: 'Speech Admin',
        email: 'admin@speech.prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 71,
          name: 'Speech',
        },
        phone_number: '',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 71,
        name: 'Speech',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 135,
      user: {
        id: 225,
        username: 'sal.part',
        first_name: 'Sal',
        display_name: 'Sal Part',
        email: 'sal@part.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 72,
          name: 'Prosa*___KiYQ',
        },
        phone_number: '0877634552',
        voice_model: null,
        last_login: '2023-05-25T13:59:22.405855',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 72,
        name: 'Prosa*___KiYQ',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 137,
      user: {
        id: 226,
        username: 'fakhri2',
        first_name: 'Fakhri',
        display_name: 'Fakhri Surya',
        email: 'lol@lol.lol',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 73,
          name: 'Fakhri nyoba Prosa*___4lOG',
        },
        phone_number: '123',
        voice_model: null,
        last_login: '2023-07-07T08:51:06.439200',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 73,
        name: 'Fakhri nyoba Prosa*___4lOG',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 139,
      user: {
        id: 228,
        username: 'pengguna_ketiga',
        first_name: 'Pengguna',
        display_name: 'Pengguna Ketiga',
        email: 'pengguna@ketiga.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 75,
          name: 'Prosa*___1pNR',
        },
        phone_number: '6285974650258',
        voice_model: null,
        last_login: '2023-06-28T10:52:56.599693',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 75,
        name: 'Prosa*___1pNR',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 140,
      user: {
        id: 229,
        username: 'fakhri3',
        first_name: 'Fakhri',
        display_name: 'Fakhri Surya Test Lagi Tiga',
        email: 'popo@popo.popo',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 76,
          name: 'Fakhri nyoba lagi 3*___qGlA',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-06-28T10:58:15',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 76,
        name: 'Fakhri nyoba lagi 3*___qGlA',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 141,
      user: {
        id: 230,
        username: 'oranga_ketiga',
        first_name: 'Orang',
        display_name: 'Orang Ketiga',
        email: 'orang@ketiga.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 77,
          name: 'Prosa*___PWhu',
        },
        phone_number: '6285156620137',
        voice_model: null,
        last_login: null,
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 77,
        name: 'Prosa*___PWhu',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 142,
      user: {
        id: 231,
        username: 'fakhri4',
        first_name: 'Nadhira',
        display_name: 'Nadhira Test',
        email: 'fakhrisurya@yahoo.co.id',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 78,
          name: 'Fakhri nyoba Prosa Nadhira*___Nmng',
        },
        phone_number: '6282122787434',
        voice_model: null,
        last_login: '2023-07-04T14:52:55.822906',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 78,
        name: 'Fakhri nyoba Prosa Nadhira*___Nmng',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 144,
      user: {
        id: 233,
        username: 'gagalhakim',
        first_name: 'Gagal',
        display_name: 'Gagal Hakim',
        email: 'hakim@mahkamah.ai',
        avatar: '/media/avatar/hakim/Hakim.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 79,
          name: 'Gagal Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model:
          '/media/voice_model/hakim/Hakim%20Enrollment_20230712_171004.wav',
        last_login: '2023-07-12T17:17:11',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 79,
        name: 'Gagal Mahkamah',
      },
      position: 'Hakim',
      department: 'Mahkamah',
      is_active: true,
      role: 'Member',
    },
    {
      id: 146,
      user: {
        id: 235,
        username: 'gagalpembawa',
        first_name: 'Gagal',
        display_name: 'Gagal Acara',
        email: 'pembawa@mahkamah.ai',
        avatar: '/media/avatar/pembawa/Pembawa.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 79,
          name: 'Gagal Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model:
          '/media/voice_model/pembawa/Pembawa%20Acara%20Enrollment_20230712_173936.wav',
        last_login: '2023-07-12T17:40:01',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 79,
        name: 'Gagal Mahkamah',
      },
      position: 'MC',
      department: 'Mahkamah',
      is_active: true,
      role: 'Member',
    },
    {
      id: 147,
      user: {
        id: 236,
        username: 'gagalpanitera_pengganti',
        first_name: 'Gagal Panitera',
        display_name: 'Gagal Panitera Pengganti',
        email: 'panitera.pengganti@mahkamah.ai',
        avatar:
          '/media/avatar/panitera_pengganti/garuda-pancasila-logo-271A8C88B7-seeklogo.com.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 79,
          name: 'Gagal Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model: null,
        last_login: '2023-07-12T17:34:11',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 79,
        name: 'Gagal Mahkamah',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 143,
      user: {
        id: 232,
        username: 'gagalpanitera',
        first_name: 'Panitera',
        display_name: 'Panitera Gagal',
        email: 'panitera@mahkamah.ai',
        avatar:
          '/media/avatar/panitera/garuda-pancasila-logo-271A8C88B7-seeklogo.com.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 79,
          name: 'Gagal Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model: '/media/voice_model/panitera/blob_20230712_173606.wav',
        last_login: '2023-07-12T17:40:12',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 79,
        name: 'Gagal Mahkamah',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 149,
      user: {
        id: 238,
        username: 'hakim',
        first_name: 'Hakim',
        display_name: 'Hakim Ketua',
        email: 'hakim@mahkamah.ecourt',
        avatar: '/media/avatar/hakim/Hakim_doe7pWA.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 80,
          name: 'Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model:
          '/media/voice_model/hakim/Hakim%20Konstitusi%20Enrollment_20230712_175705.wav',
        last_login: '2023-07-12T17:57:57',
        count_participated_meetings: 7,
        count_attended_meetings: 0,
      },
      organization: {
        id: 80,
        name: 'Mahkamah',
      },
      position: 'Hakim',
      department: 'Mahkamah',
      is_active: true,
      role: 'Member',
    },
    {
      id: 150,
      user: {
        id: 239,
        username: 'kuasa',
        first_name: 'Kuasa',
        display_name: 'Kuasa Hukum',
        email: 'kuasa@mahkamah.ecourt',
        avatar: '/media/avatar/kuasa/Kuasa.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 80,
          name: 'Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model:
          '/media/voice_model/kuasa/Kuasa%20Hukum%20Enrollment_20230713_111456.wav',
        last_login: '2023-07-13T11:18:13.717084',
        count_participated_meetings: 7,
        count_attended_meetings: 0,
      },
      organization: {
        id: 80,
        name: 'Mahkamah',
      },
      position: 'Kuasa Hukum',
      department: 'Mahkamah',
      is_active: true,
      role: 'Member',
    },
    {
      id: 152,
      user: {
        id: 241,
        username: 'panitera.pengganti',
        first_name: 'Panitera',
        display_name: 'Panitera Pengganti',
        email: 'panitera.pengganti@mahkamah.ecourt',
        avatar:
          '/media/avatar/panitera.pengganti/garuda-pancasila-logo-271A8C88B7-seeklogo.com.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 80,
          name: 'Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model: null,
        last_login: '2023-07-13T08:53:50.631171',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 80,
        name: 'Mahkamah',
      },
      position: 'Panitera',
      department: 'Mahkamah',
      is_active: true,
      role: 'Member',
    },
    {
      id: 148,
      user: {
        id: 237,
        username: 'panitera',
        first_name: 'Panitera',
        display_name: 'Panitera Sidang',
        email: 'panitera@mahkamah.ecourt',
        avatar:
          '/media/avatar/panitera/garuda-pancasila-logo-271A8C88B7-seeklogo.com_veXEcCg.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 80,
          name: 'Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model:
          '/media/voice_model/panitera/Enrollment%20Fakhri%20Surya_20230713_084328.wav',
        last_login: '2023-07-20T10:28:14.711384',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 80,
        name: 'Mahkamah',
      },
      position: 'Panitera',
      department: 'Mahkamah',
      is_active: true,
      role: 'Member',
    },
    {
      id: 151,
      user: {
        id: 240,
        username: 'pembawa',
        first_name: 'Pembawa',
        display_name: 'Pembawa Acara',
        email: 'pembawa@mahkamah.ecourt',
        avatar: '/media/avatar/pembawa/Pembawa_4pStlTZ.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 80,
          name: 'Mahkamah',
        },
        phone_number: '62000000000000',
        voice_model:
          '/media/voice_model/pembawa/Pembawa%20Acara%20Enrollment_20230712_175742.wav',
        last_login: '2023-07-12T17:58:35',
        count_participated_meetings: 7,
        count_attended_meetings: 0,
      },
      organization: {
        id: 80,
        name: 'Mahkamah',
      },
      position: 'Pembawa Acara',
      department: 'Mahkamah',
      is_active: true,
      role: 'Member',
    },
    {
      id: 153,
      user: {
        id: 242,
        username: 'test_register',
        first_name: 'test',
        display_name: 'test register',
        email: 'test@mail.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 81,
          name: 'test*___WRpQ',
        },
        phone_number: '6285216286520',
        voice_model: null,
        last_login: '2023-07-13T10:18:09.808581',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 81,
        name: 'test*___WRpQ',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 154,
      user: {
        id: 243,
        username: 'fakhri',
        first_name: 'Fakhri',
        display_name: 'Fakhri Uhuy',
        email: 'fakhri.surya@prosa.ai',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 82,
          name: 'Fakhri Uhuy*___vuN1',
        },
        phone_number: '6285217730694',
        voice_model: null,
        last_login: '2023-08-04T08:47:44.614792',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 82,
        name: 'Fakhri Uhuy*___vuN1',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Trial',
    },
    {
      id: 155,
      user: {
        id: 244,
        username: 'marvin',
        first_name: 'Marvin',
        display_name: 'Marvin Jerremy',
        email: 'marvin@example.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 83,
          name: 'Marvin Add Term',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-10-03T18:12:09.449667',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 83,
        name: 'Marvin Add Term',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Admin',
    },
    {
      id: 157,
      user: {
        id: 246,
        username: 'trial_dictionary',
        first_name: 'Trial',
        display_name: 'Trial Dictionary',
        email: 'trial@add.term',
        avatar: null,
        enrollment_status: 'enrolled',
        is_enrolling: false,
        organization: {
          id: 85,
          name: 'Trial Add Term',
        },
        phone_number: '62000000000',
        voice_model:
          '/media/voice_model/trial_dictionary/Enrollment_Fakhri_Surya.wav',
        last_login: '2023-10-10T14:07:10.225089',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 85,
        name: 'Trial Add Term',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 158,
      user: {
        id: 247,
        username: 'nad_oov',
        first_name: 'Nadira',
        display_name: 'Nadira OOV Arthamevia',
        email: 'arthamevia.backup@gmail.com',
        avatar: '/media/avatar/nad_oov/sticker_meal_ville_1_1.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 86,
          name: 'TLKM*___ACbm',
        },
        phone_number: '6281212923787',
        voice_model: null,
        last_login: '2023-10-09T15:30:35.060036',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 86,
        name: 'TLKM*___ACbm',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Admin',
    },
    {
      id: 173,
      user: {
        id: 272,
        username: 'anna',
        first_name: 'Anna',
        display_name: 'Anna Belle',
        email: 'anna@english.meemo',
        avatar: '/media/avatar/anna/4086609.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 97,
          name: 'Trial MSIG',
        },
        phone_number: '62000000000',
        voice_model: '/media/voice_model/anna/Anna_20230822_174351.wav',
        last_login: '2023-08-22T17:44:37.861523',
        count_participated_meetings: 3,
        count_attended_meetings: 0,
      },
      organization: {
        id: 97,
        name: 'Trial MSIG',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 171,
      user: {
        id: 270,
        username: 'david',
        first_name: 'David',
        display_name: 'David Cho',
        email: 'david@english.meemo',
        avatar: '/media/avatar/david/Menteri.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 97,
          name: 'Trial MSIG',
        },
        phone_number: '62000000',
        voice_model: '/media/voice_model/david/David%203_20230824_094942.wav',
        last_login: '2023-08-24T09:50:22.773661',
        count_participated_meetings: 3,
        count_attended_meetings: 0,
      },
      organization: {
        id: 97,
        name: 'Trial MSIG',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 170,
      user: {
        id: 269,
        username: 'marcus',
        first_name: 'Marcus',
        display_name: 'Marcus Lionel',
        email: 'marcus@english.meemo',
        avatar: '/media/avatar/marcus/1255974.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 97,
          name: 'Trial MSIG',
        },
        phone_number: '62000000000',
        voice_model: '/media/voice_model/marcus/Marcus_20230822_174512.wav',
        last_login: '2023-08-22T17:44:46.782066',
        count_participated_meetings: 3,
        count_attended_meetings: 0,
      },
      organization: {
        id: 97,
        name: 'Trial MSIG',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 172,
      user: {
        id: 271,
        username: 'maya',
        first_name: 'Maya',
        display_name: 'Maya Watsons',
        email: 'maya@english.meemo',
        avatar: '/media/avatar/maya/6960093.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 97,
          name: 'Trial MSIG',
        },
        phone_number: '62000000000',
        voice_model: '/media/voice_model/maya/Maya_20230822_174420.wav',
        last_login: '2023-08-22T17:44:11.606470',
        count_participated_meetings: 3,
        count_attended_meetings: 0,
      },
      organization: {
        id: 97,
        name: 'Trial MSIG',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 169,
      user: {
        id: 268,
        username: 'msig',
        first_name: 'Trial',
        display_name: 'Trial MSIG',
        email: 'trial@english.meemo',
        avatar: '/media/avatar/msig/download.png',
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 97,
          name: 'Trial MSIG',
        },
        phone_number: '62000000',
        voice_model: null,
        last_login: '2023-08-25T15:33:35.667562',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 97,
        name: 'Trial MSIG',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Admin',
    },
    {
      id: 178,
      user: {
        id: 277,
        username: 'fakhri_qav3',
        first_name: 'Admin',
        display_name: 'Admin Fakhri',
        email: 'fakhri@qav3.com',
        avatar: null,
        enrollment_status: 'not_enrolled',
        is_enrolling: false,
        organization: {
          id: 99,
          name: 'QA v3',
        },
        phone_number: '',
        voice_model: null,
        last_login: '2023-10-11T11:25:39.649772',
        count_participated_meetings: 0,
        count_attended_meetings: 0,
      },
      organization: {
        id: 99,
        name: 'QA v3',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 175,
      user: {
        id: 274,
        username: 'ami_qav3',
        first_name: 'Kak',
        display_name: 'Kak Ami',
        email: 'ami@qav3.com',
        avatar: null,
        enrollment_status: 'enrolled',
        is_enrolling: false,
        organization: {
          id: 99,
          name: 'QA v3',
        },
        phone_number: '',
        voice_model: '/media/voice_model/ami_qav3/rahmi.yuwan_voice.wav',
        last_login: '2023-10-06T15:47:28.715999',
        count_participated_meetings: 2,
        count_attended_meetings: 0,
      },
      organization: {
        id: 99,
        name: 'QA v3',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 174,
      user: {
        id: 273,
        username: 'erlin_qav3',
        first_name: 'Kak',
        display_name: 'Kak Erlin',
        email: 'erlin@qav3.com',
        avatar: null,
        enrollment_status: 'enrolled',
        is_enrolling: false,
        organization: {
          id: 99,
          name: 'QA v3',
        },
        phone_number: '',
        voice_model: '/media/voice_model/erlin_qav3/erlin_voice.wav',
        last_login: '2023-10-06T15:47:03.875607',
        count_participated_meetings: 2,
        count_attended_meetings: 0,
      },
      organization: {
        id: 99,
        name: 'QA v3',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 176,
      user: {
        id: 275,
        username: 'reza_qav3',
        first_name: 'Kak',
        display_name: 'Kak Reza',
        email: 'reza@qav3.com',
        avatar: null,
        enrollment_status: 'enrolled',
        is_enrolling: false,
        organization: {
          id: 99,
          name: 'QA v3',
        },
        phone_number: '',
        voice_model: '/media/voice_model/reza_qav3/sazky_voice.wav',
        last_login: '2023-10-06T15:48:24.077647',
        count_participated_meetings: 2,
        count_attended_meetings: 0,
      },
      organization: {
        id: 99,
        name: 'QA v3',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
    {
      id: 177,
      user: {
        id: 276,
        username: 'ica_qav3',
        first_name: 'Teh',
        display_name: 'Teh Ica',
        email: 'ica@qav3.com',
        avatar: null,
        enrollment_status: 'enrolled',
        is_enrolling: false,
        organization: {
          id: 99,
          name: 'QA v3',
        },
        phone_number: '',
        voice_model: '/media/voice_model/ica_qav3/trisa_voice.wav',
        last_login: '2023-10-06T15:49:15.743018',
        count_participated_meetings: 2,
        count_attended_meetings: 0,
      },
      organization: {
        id: 99,
        name: 'QA v3',
      },
      position: null,
      department: null,
      is_active: true,
      role: 'Member',
    },
  ],
}

export interface MemberSimplified {
  idMember: number
  name: string
  isMember: boolean
  idUser: number
}

export const members = rawData.results.map<MemberSimplified>((member) => ({
  idMember: member.id,
  name: member.user.display_name,
  isMember: true,
  idUser: member.user.id,
}))

export interface Groups {
  name: string
  members: MemberSimplified[]
}

export const groups: Groups[] = [
  {
    name: 'group 1',
    members: [members[3], members[6], members[8]],
  },
  {
    name: 'group 2',
    members: [members[1], members[2], members[8]],
  },
]
